name: "Setup build environment"
description: "Checks out code, sets up Java and Gradle with appropriate configuration"
inputs:
  gradle-cache-encryption-key:
    required: true
    description: "Key used to encrypt Gradle build cache"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Copy CI gradle.properties
      shell: bash
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
      with:
        cache-encryption-key: ${{ inputs.gradle_cache_encryption_key }}
