name: "Setup build environment"
description: "Checks out code, sets up Java and Gradle with appropriate configuration"
inputs:
  gradle-cache-encryption-key:
    required: true
    description: "Key used to encrypt Gradle build cache"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Copy CI gradle.properties
      shell: bash
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5
      with:
        cache-encryption-key: ${{ inputs.gradle_cache_encryption_key }}
