name: "Setup build environment"
description: "Checks out code, sets up Java and Gradle with appropriate configuration"
inputs:
  gradle-cache-encryption-key:
    required: true
    description: "Key used to encrypt Gradle build cache"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Copy CI gradle.properties
      shell: bash
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      with:
        cache-encryption-key: ${{ inputs.gradle_cache_encryption_key }}
