/*
 * Copyright (c) 2026 Pachli Association
 *
 * This file is a part of Pachli.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation; either version 3 of the
 * License, or (at your option) any later version.
 *
 * Pachli is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Pachli; if not,
 * see <http://www.gnu.org/licenses>.
 */

package app.pachli.core.designsystem.theme
import androidx.compose.ui.graphics.Color

// Material colour definitions.

internal val primaryLight = Color(0xFF166683)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFC0E8FF)
internal val onPrimaryContainerLight = Color(0xFF004D66)
internal val secondaryLight = Color(0xFF4D616C)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFD0E6F3)
internal val onSecondaryContainerLight = Color(0xFF364954)
internal val tertiaryLight = Color(0xFF5E5A7D)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFE4DFFF)
internal val onTertiaryContainerLight = Color(0xFF464364)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFF6FAFE)
internal val onBackgroundLight = Color(0xFF171C1F)
internal val surfaceLight = Color(0xFFF6FAFE)
internal val onSurfaceLight = Color(0xFF171C1F)
internal val surfaceVariantLight = Color(0xFFDCE3E9)
internal val onSurfaceVariantLight = Color(0xFF40484C)
internal val outlineLight = Color(0xFF71787D)
internal val outlineVariantLight = Color(0xFFC0C7CD)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2C3134)
internal val inverseOnSurfaceLight = Color(0xFFEDF1F5)
internal val inversePrimaryLight = Color(0xFF8DCFF1)
internal val surfaceDimLight = Color(0xFFD6DADE)
internal val surfaceBrightLight = Color(0xFFF6FAFE)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF0F4F8)
internal val surfaceContainerLight = Color(0xFFEAEEF2)
internal val surfaceContainerHighLight = Color(0xFFE4E9EC)
internal val surfaceContainerHighestLight = Color(0xFFDFE3E7)

internal val primaryLightMediumContrast = Color(0xFF003B4F)
internal val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val primaryContainerLightMediumContrast = Color(0xFF2C7593)
internal val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val secondaryLightMediumContrast = Color(0xFF253943)
internal val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val secondaryContainerLightMediumContrast = Color(0xFF5C707B)
internal val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val tertiaryLightMediumContrast = Color(0xFF363252)
internal val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val tertiaryContainerLightMediumContrast = Color(0xFF6D698D)
internal val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val errorLightMediumContrast = Color(0xFF740006)
internal val onErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val errorContainerLightMediumContrast = Color(0xFFCF2C27)
internal val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val backgroundLightMediumContrast = Color(0xFFF6FAFE)
internal val onBackgroundLightMediumContrast = Color(0xFF171C1F)
internal val surfaceLightMediumContrast = Color(0xFFF6FAFE)
internal val onSurfaceLightMediumContrast = Color(0xFF0D1215)
internal val surfaceVariantLightMediumContrast = Color(0xFFDCE3E9)
internal val onSurfaceVariantLightMediumContrast = Color(0xFF30373C)
internal val outlineLightMediumContrast = Color(0xFF4C5358)
internal val outlineVariantLightMediumContrast = Color(0xFF676E73)
internal val scrimLightMediumContrast = Color(0xFF000000)
internal val inverseSurfaceLightMediumContrast = Color(0xFF2C3134)
internal val inverseOnSurfaceLightMediumContrast = Color(0xFFEDF1F5)
internal val inversePrimaryLightMediumContrast = Color(0xFF8DCFF1)
internal val surfaceDimLightMediumContrast = Color(0xFFC3C7CB)
internal val surfaceBrightLightMediumContrast = Color(0xFFF6FAFE)
internal val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightMediumContrast = Color(0xFFF0F4F8)
internal val surfaceContainerLightMediumContrast = Color(0xFFE4E9EC)
internal val surfaceContainerHighLightMediumContrast = Color(0xFFD9DDE1)
internal val surfaceContainerHighestLightMediumContrast = Color(0xFFCED2D6)

internal val primaryLightHighContrast = Color(0xFF003041)
internal val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val primaryContainerLightHighContrast = Color(0xFF004F69)
internal val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val secondaryLightHighContrast = Color(0xFF1B2F38)
internal val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val secondaryContainerLightHighContrast = Color(0xFF384C56)
internal val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryLightHighContrast = Color(0xFF2B2848)
internal val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryContainerLightHighContrast = Color(0xFF494567)
internal val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val errorLightHighContrast = Color(0xFF600004)
internal val onErrorLightHighContrast = Color(0xFFFFFFFF)
internal val errorContainerLightHighContrast = Color(0xFF98000A)
internal val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val backgroundLightHighContrast = Color(0xFFF6FAFE)
internal val onBackgroundLightHighContrast = Color(0xFF171C1F)
internal val surfaceLightHighContrast = Color(0xFFF6FAFE)
internal val onSurfaceLightHighContrast = Color(0xFF000000)
internal val surfaceVariantLightHighContrast = Color(0xFFDCE3E9)
internal val onSurfaceVariantLightHighContrast = Color(0xFF000000)
internal val outlineLightHighContrast = Color(0xFF262D31)
internal val outlineVariantLightHighContrast = Color(0xFF434A4F)
internal val scrimLightHighContrast = Color(0xFF000000)
internal val inverseSurfaceLightHighContrast = Color(0xFF2C3134)
internal val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val inversePrimaryLightHighContrast = Color(0xFF8DCFF1)
internal val surfaceDimLightHighContrast = Color(0xFFB5B9BD)
internal val surfaceBrightLightHighContrast = Color(0xFFF6FAFE)
internal val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightHighContrast = Color(0xFFEDF1F5)
internal val surfaceContainerLightHighContrast = Color(0xFFDFE3E7)
internal val surfaceContainerHighLightHighContrast = Color(0xFFD1D5D9)
internal val surfaceContainerHighestLightHighContrast = Color(0xFFC3C7CB)

internal val primaryDark = Color(0xFF8DCFF1)
internal val onPrimaryDark = Color(0xFF003547)
internal val primaryContainerDark = Color(0xFF004D66)
internal val onPrimaryContainerDark = Color(0xFFC0E8FF)
internal val secondaryDark = Color(0xFFB4CAD6)
internal val onSecondaryDark = Color(0xFF1F333D)
internal val secondaryContainerDark = Color(0xFF364954)
internal val onSecondaryContainerDark = Color(0xFFD0E6F3)
internal val tertiaryDark = Color(0xFFC7C2EA)
internal val onTertiaryDark = Color(0xFF302D4C)
internal val tertiaryContainerDark = Color(0xFF464364)
internal val onTertiaryContainerDark = Color(0xFFE4DFFF)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF0F1417)
internal val onBackgroundDark = Color(0xFFDFE3E7)
internal val surfaceDark = Color(0xFF0F1417)
internal val onSurfaceDark = Color(0xFFDFE3E7)
internal val surfaceVariantDark = Color(0xFF40484C)
internal val onSurfaceVariantDark = Color(0xFFC0C7CD)
internal val outlineDark = Color(0xFF8A9297)
internal val outlineVariantDark = Color(0xFF40484C)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFDFE3E7)
internal val inverseOnSurfaceDark = Color(0xFF2C3134)
internal val inversePrimaryDark = Color(0xFF166683)
internal val surfaceDimDark = Color(0xFF0F1417)
internal val surfaceBrightDark = Color(0xFF353A3D)
internal val surfaceContainerLowestDark = Color(0xFF0A0F12)
internal val surfaceContainerLowDark = Color(0xFF171C1F)
internal val surfaceContainerDark = Color(0xFF1B2023)
internal val surfaceContainerHighDark = Color(0xFF262B2E)
internal val surfaceContainerHighestDark = Color(0xFF303539)

internal val primaryDarkMediumContrast = Color(0xFFB0E3FF)
internal val onPrimaryDarkMediumContrast = Color(0xFF002938)
internal val primaryContainerDarkMediumContrast = Color(0xFF5599B8)
internal val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
internal val secondaryDarkMediumContrast = Color(0xFFCADFEC)
internal val onSecondaryDarkMediumContrast = Color(0xFF142832)
internal val secondaryContainerDarkMediumContrast = Color(0xFF7F94A0)
internal val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val tertiaryDarkMediumContrast = Color(0xFFDED8FF)
internal val onTertiaryDarkMediumContrast = Color(0xFF252241)
internal val tertiaryContainerDarkMediumContrast = Color(0xFF918CB2)
internal val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
internal val errorDarkMediumContrast = Color(0xFFFFD2CC)
internal val onErrorDarkMediumContrast = Color(0xFF540003)
internal val errorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val onErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val backgroundDarkMediumContrast = Color(0xFF0F1417)
internal val onBackgroundDarkMediumContrast = Color(0xFFDFE3E7)
internal val surfaceDarkMediumContrast = Color(0xFF0F1417)
internal val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val surfaceVariantDarkMediumContrast = Color(0xFF40484C)
internal val onSurfaceVariantDarkMediumContrast = Color(0xFFD6DDE3)
internal val outlineDarkMediumContrast = Color(0xFFABB3B8)
internal val outlineVariantDarkMediumContrast = Color(0xFF8A9196)
internal val scrimDarkMediumContrast = Color(0xFF000000)
internal val inverseSurfaceDarkMediumContrast = Color(0xFFDFE3E7)
internal val inverseOnSurfaceDarkMediumContrast = Color(0xFF262B2E)
internal val inversePrimaryDarkMediumContrast = Color(0xFF004E67)
internal val surfaceDimDarkMediumContrast = Color(0xFF0F1417)
internal val surfaceBrightDarkMediumContrast = Color(0xFF404548)
internal val surfaceContainerLowestDarkMediumContrast = Color(0xFF04080A)
internal val surfaceContainerLowDarkMediumContrast = Color(0xFF191E21)
internal val surfaceContainerDarkMediumContrast = Color(0xFF24292C)
internal val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3336)
internal val surfaceContainerHighestDarkMediumContrast = Color(0xFF393E41)

internal val primaryDarkHighContrast = Color(0xFFDFF3FF)
internal val onPrimaryDarkHighContrast = Color(0xFF000000)
internal val primaryContainerDarkHighContrast = Color(0xFF89CBED)
internal val onPrimaryContainerDarkHighContrast = Color(0xFF000D14)
internal val secondaryDarkHighContrast = Color(0xFFDFF3FF)
internal val onSecondaryDarkHighContrast = Color(0xFF000000)
internal val secondaryContainerDarkHighContrast = Color(0xFFB1C6D2)
internal val onSecondaryContainerDarkHighContrast = Color(0xFF000D14)
internal val tertiaryDarkHighContrast = Color(0xFFF2EDFF)
internal val onTertiaryDarkHighContrast = Color(0xFF000000)
internal val tertiaryContainerDarkHighContrast = Color(0xFFC4BEE6)
internal val onTertiaryContainerDarkHighContrast = Color(0xFF0A0625)
internal val errorDarkHighContrast = Color(0xFFFFECE9)
internal val onErrorDarkHighContrast = Color(0xFF000000)
internal val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
internal val onErrorContainerDarkHighContrast = Color(0xFF220001)
internal val backgroundDarkHighContrast = Color(0xFF0F1417)
internal val onBackgroundDarkHighContrast = Color(0xFFDFE3E7)
internal val surfaceDarkHighContrast = Color(0xFF0F1417)
internal val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val surfaceVariantDarkHighContrast = Color(0xFF40484C)
internal val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val outlineDarkHighContrast = Color(0xFFEAF1F7)
internal val outlineVariantDarkHighContrast = Color(0xFFBCC4C9)
internal val scrimDarkHighContrast = Color(0xFF000000)
internal val inverseSurfaceDarkHighContrast = Color(0xFFDFE3E7)
internal val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val inversePrimaryDarkHighContrast = Color(0xFF004E67)
internal val surfaceDimDarkHighContrast = Color(0xFF0F1417)
internal val surfaceBrightDarkHighContrast = Color(0xFF4C5154)
internal val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val surfaceContainerLowDarkHighContrast = Color(0xFF1B2023)
internal val surfaceContainerDarkHighContrast = Color(0xFF2C3134)
internal val surfaceContainerHighDarkHighContrast = Color(0xFF373C3F)
internal val surfaceContainerHighestDarkHighContrast = Color(0xFF42474B)

internal val onPrimaryBlack = Color.Black
internal val backgroundBlack = Color.Black
internal val surfaceBlack = tuskyGrey10
internal val surfaceContainerLowestBlack = tuskyGrey10
internal val surfaceContainerLowBlack = tuskyGrey10
internal val surfaceContainerBlack = tuskyGrey10
internal val surfaceContainerHighBlack = tuskyGrey10
internal val surfaceContainerHighestBlack = tuskyGrey10
