name: reviewdog-suggester
on: pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  ktlint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - run: chmod +x ./gradlew

      - run: ./gradlew ktlintFormat

      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: ktlintFormat
