# Build the app on each push to `main`, populating the build cache to speed
# up CI on PRs.

name: Populate build cache

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        color: ["orange"]
        store: ["fdroid", "github", "google"]
    name: app:buildOrangeDebug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Run app:buildOrangeDebug
        run: ./gradlew app:build${{ matrix.color }}${{ matrix.store }}Debug
