# Build the app on each push to `main`, populating the build cache to speed
# up CI on PRs.

name: Populate build cache

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        color: ["orange"]
        store: ["fdroid", "github", "google"]
    name: app:buildOrangeDebug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92 # v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run app:buildOrangeDebug
        run: ./gradlew app:build${{ matrix.color }}${{ matrix.store }}Debug
