# Build the app on each push to `main`, populating the build cache to speed
# up CI on PRs.

name: Populate build cache

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        color: ["orange"]
        store: ["fdroid", "github", "google"]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: ./.github/actions/setup-build-env
        with:
          gradle-cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build ${{ matrix.color }}${{ matrix.store }}Debug
        run: ./gradlew build${{ matrix.color }}${{ matrix.store }}Debug
